---
- hosts: mongodb_all
  remote_user: "{{ansible_ssh_user}}"
  tasks:
#    - openssl_privatekey:
#      path: ~/mongo-project/mongo.key
    - name: Creates directory
      file: path={{MONGO_DIR}} state=directory
    - name: Upload key file 
      copy:
        src: ../work/mongo.key
        dest: "{{MONGO_DIR}}/mongo.key"
#        owner: cc
#        group: cc
        mode: 0700

#http://docs.ansible.com/ansible/copy_module.html
#http://stackoverflow.com/questions/22844905/how-to-create-a-directory-using-ansible
#http://stackoverflow.com/questions/18900236/run-command-on-the-ansible-host

