---
- hosts: mongodb_all
  remote_user: "{{ansible_ssh_user}}"
  tasks:
   - name: Import the public key used by the package management system
     apt_key: id=EA312927  keyserver=hkp://keyserver.ubuntu.com:80
     become: true
   - name: Add the repository
     apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state=present
#next is 3.4 on 14.04
#     apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse' state=present
     become: true
   - name: install the packages
     apt: pkg=mongodb-org state=present
     become: true

#https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
#http://stackoverflow.com/questions/37568848/how-to-install-mongodb-with-ansible
