---
galaxy_info:
  author: Scott McClary
  description: Deployment of Hadoop Cluster on Chameleon Cloud
  company: Indiana University
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - development

dependencies: []
