- name: Step 1 of 7 -> Run CDMS Serial Applicaton
  shell: source /home/cc/intel/bin/compilervars.sh intel64 && ulimit -S -s 120000 && cd /home/cc/data && /home/cc/cloudmesh.cdms-master/code/trap_analysis/trap >> /home/cc/serial_output.txt
  args:
     executable: /bin/bash

- name: Step 2 of 7 -> Run CDMS OpenMP Applicaton
  shell: source /home/cc/intel/bin/compilervars.sh intel64 && ulimit -S -s 120000 && export OMP_STACKSIZE=100M && cd /home/cc/data && /home/cc/cloudmesh.cdms-master/code/trap_analysis/trap_omp >> /home/cc/omp_output.txt
  args:
     executable: /bin/bash

- name: Step 3 of 7 -> Convert CDMS Data
  shell: cd /home/cc/data && /home/cc/cloudmesh.cdms-master/code/scripts/binary_to_text.sh
  args:
     executable: /bin/bash

- name: Step 4 of 7 -> Put CDMS Data in HDFS
  sudo: yes
  shell: su - hadoop -c "hadoop fs -mkdir /cdms" && su - hadoop -c "hadoop fs -mkdir /cdms/input" && su - hadoop -c "hadoop fs -put /home/cc/data/chA*.txt /cdms/input/"
  args:
     executable: /bin/bash

#- name: Step 5 of 7 -> Run CDMS Hadoop Application
#  sudo: yes
#  shell: |
#     su - hadoop -c "hadoop jar /opt/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar -D mapreduce.input.fileinputformat.split.minsize=7090910 -input /cdms/input -output /cdms/output -mapper /home/cc/cloudmesh.cdms-master/code/trap_analysis/trap_hadoop -reducer /bin/cat"

#- name: Step 6 of 7 -> Get CDMS Hadoop Output
#  sudo: yes
#  shell: |
#     su - hadoop -c "hadoop fs -get /cdms/output/part-00000"

- name: Step 7 of 7 -> Clean HDFS
  sudo: yes
  shell: |
     su - hadoop -c "hadoop fs -rm /cdms/input/*"
     su - hadoop -c "hadoop fs -rmdir /cdms/input"
     su - hadoop -c "hadoop fs -rmdir /cdms"
#     su - hadoop -c "hadoop fs -rm /cdms/output/*"
#     su - hadoop -c "hadoop fs -rmdir /cdms/output"
