---
- name: add nodejs GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  become: yes
  tags:
  - nodejs

- name: add nodejs repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{nodejs_version}} wheezy main"
    state: present
  become: yes
  register: nodejs_repo_added
  tags:
  - nodejs

- name: apt update cache
  apt:
    update_cache: yes
  become: yes
  when: nodejs_repo_added.changed
  tags:
  - nodejs

- name: install nodejs package
  apt:
    pkg: nodejs
    state: present
  become: yes
  tags:
  - nodejs

- name: install git       
  apt: name=git state=present update_cache=yes
  become: yes

- name: git_config
  become_user: root
  shell: |
    git config --global user.name "Sriram Sitharaman"
    git config --global user.email sriramsitharaman@gmail.com
    